name: Secrets import
on:
  workflow_dispatch:
  push:
      branches:
        - master
  
jobs:  
  checkout_linux_runner:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3 
    
    - id: 'GCP-Auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_API_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      
    - name: 'GCP SETUP'
      uses: 'google-github-actions/setup-gcloud@v0.6.0'
      with:
        project_id: 'workflowspractice'
    # - name: secret import with env
    #   env:
    #       SUPER_SECRET: ${{ secrets.SECRET_NOQT }}
    #   run: echo "$SUPER_SECRET" | gcloud secrets create clinical_env_secrets --project=workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4
   # echo '${{secrets.SECRET_NOQT}}' | gcloud secrets create secrets_sq_TRIAL --project=workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4
    - name: secrets import without env
      env:
           SECRET_GE_ENV: ${{ secrets.RP_UNIX_VARIABLE_TEST }}
      run: | 
         echo "Secrets creation started"
         echo -n "$SECRET_GE_ENV" | gcloud secrets create unix_variable_test_env_N --project=workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4        
         echo "$SECRET_GE_ENV" | gcloud secrets create unix_variable_test_env --project=workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4  
  

         # echo "${{ secrets.RP_UNIX_VARIABLE_TEST }}" | gcloud secrets create unix_variable_test_double --project=workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4
         # echo -n '${{ secrets.RP_UNIX_VARIABLE_TEST }}' | gcloud secrets create unix_variable_test_single_N --project==workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4
         # echo '${{ secrets.RP_UNIX_VARIABLE_TEST }}' | gcloud secrets create test_secret_spec_char --project=workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4
         # echo '${{ secrets.RP_UNIX_VARIABLE_TEST }}' | gcloud secrets create unix_variable_test_single --project=workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4
         
         # echo -n "${{ secrets.RP_UNIX_VARIABLE_TEST }}" | gcloud secrets create unix_variable_test_double_N --project=${{ env.infra_env_v_proc_project_id }} --data-file=- --replication-policy=user-managed --locations=us-east4
         # echo -n "$SECRET_GE_ENV" | gcloud secrets create unix_variable_test_env_N --project=${{ env.infra_env_v_proc_project_id }} --data-file=- --replication-policy=user-managed --locations=us-east4        
         # echo "$SECRET_GE_ENV" | gcloud secrets create unix_variable_test_env --project=${{ env.infra_env_v_proc_project_id }} --data-file=- --replication-policy=user-managed --locations=us-east4  
  

