name: Special character in github secrets
on:
  workflow_dispatch:
  push:
      branches:
        - master
jobs:  
  checkout_linux_runner:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3 
          # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    # env and single quote will resolve the issue of special character in github secrets. we can use any of these 2 solutions
    - name: Run a one-line script
      env:
        SUPER_SECRET: ${{ secrets.SECRET_NOQT }}
      run: echo "$SUPER_SECRET" | sed 's/./& /g'
     # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo '${{ secrets.SECRET_NOQT  }}' | sed 's/./& /g'
  
    
