name: Secrets
on:
  workflow_dispatch:
  push:
      branches:
        - master
    
  
# env:
#   SECRET_MANUALLY: araj$vbc9!

jobs:  
  checkout_linux_runner:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3 
    # - name: secret value check
    #   run: echo "${{secrets.SECRET_NOQT}}" | sed s/./& /g
    - name: Get Secret Value
      run: |
        ESCAPED_SECRET_VALUE=$(echo "$SECRET_NOQT" | sed 's/\$/\\$/g')
        echo "value: $ESCAPED_SECRET_VALUE"
      # run: |
      #   SECRET_VALUE="${{ secrets.SECRET_NOQT }}"
      #   echo "Secret Value: $SECRET_VALUE" | sed s/./& /g
  
      
