name: Secrets
on:
  workflow_dispatch:
  push:
      branches:
        - master
  

jobs:  
  checkout_linux_runner:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: using sed cmd
      run: echo " "${{secrets.SECRET_NOQT}}" | sed s/./& /g "

  
      
