name: Secrets
on:
  workflow_dispatch:
  
env:
  secret_manually: Monday

jobs:  

  checkout_linux_runner:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: secret value check
      run: echo "${{secret.secret_manually}}" | sed s/./& /g
  
      
