name: Secrets
on:
  workflow_dispatch:
  # push:
  #     branches:
  #       - master
  

jobs:  
  checkout_linux_runner:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3 
    
    # - id: 'GCP-Auth'
    #   name: 'Authenticate to Google Cloud'
    #   uses: 'google-github-actions/auth@v1'
    #   with:
    #     credentials_json: ${{ secrets.GCP_API_KEY }}

    # - name: 'Set up Cloud SDK'
    #   uses: 'google-github-actions/setup-gcloud@v1'
      
    # - name: 'GCP SETUP'
    #   uses: 'google-github-actions/setup-gcloud@v0.6.0'
    #   with:
    #     project_id: 'workflowspractice'
    - name: secret value
      # env:
      #     SUPER_SECRET: ${{ secrets.SECRET_NOQT }}
      run: |
        echo '${{secrets.SECRET_NOQT}}' 
        echo "secrest: ${{secrets.SECRET_NOQT}}"
      
      #| gcloud secrets create secrets_sq --project=workflowspractice --data-file=- --replication-policy=user-managed --locations=us-east4
      # run: |
      #   echo ${{secrets.SECRET_NOQT}}
      #   echo "${{secrets.SECRET_NOQT}}" | sed 's/./& /g'
    #   run: |
    #     SECRET_VALUE="${{ secrets.SECRET_NOQT }}"
    #     echo "secret val: $SECRET_VALUE"
    # - name: Escape Special Characters in Secret Value
    #   id: escape_special_characters
    #   run: |
    #     ESCAPED_SECRET_VALUE=$(echo "${{ secrets.SECRET_NOQT }}" | sed 's/./& /g')
    #     echo "::set-output name=escaped_secret_value::$ESCAPED_SECRET_VALUE"
    # - name: escaped secret value output
    #   run: echo "$ESCAPED_SECRET_VALUE"



  
      
