name: Secrets
on:
  workflow_dispatch:
  
env:
  SECRET_MANUALLY: araj$vbc9!

jobs:  

  checkout_linux_runner:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: secret value check
      run: echo "${{env.SECRET_MANUALLY}}" | sed s/./& /g
  
      
